import type { Metadata } from "next";
import {open_sans, pt_serif} from "@/app/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${open_sans.variable} ${pt_serif.variable}`}>{children}</body>
    </html>
  );
}
