/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
    collections: {
        users: User;
        media: Media;
        pages: Page;
        'payload-preferences': PayloadPreference;
        'payload-migrations': PayloadMigration;
    };
    globals: {
        navigation: Navigation;
        'site-options': SiteOption;
    };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
    id: number;
    role?: 'admin' | null;
    updatedAt: string;
    createdAt: string;
    email: string;
    resetPasswordToken?: string | null;
    resetPasswordExpiration?: string | null;
    salt?: string | null;
    hash?: string | null;
    loginAttempts?: number | null;
    lockUntil?: string | null;
    password: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
    id: number;
    alt?: string | null;
    updatedAt: string;
    createdAt: string;
    url?: string | null;
    filename?: string | null;
    mimeType?: string | null;
    filesize?: number | null;
    width?: number | null;
    height?: number | null;
    focalX?: number | null;
    focalY?: number | null;
    sizes?: {
        thumbnail?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        card?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
        tablet?: {
            url?: string | null;
            width?: number | null;
            height?: number | null;
            mimeType?: string | null;
            filesize?: number | null;
            filename?: string | null;
        };
    };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
    id: number;
    jump_menu?:
        | {
        title?: string | null;
        link?: {
            relationTo: 'pages';
            value: number | Page;
        } | null;
        internal_link?: string | null;
        id?: string | null;
    }[]
        | null;
    title: string;
    slug?: string | null;
    publishedAt?: string | null;
    featuredImage?: number | Media | null;
    updatedAt: string;
    createdAt: string;
    _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
    id: number;
    user: {
        relationTo: 'users';
        value: number | User;
    };
    key?: string | null;
    value?:
        | {
        [k: string]: unknown;
    }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
    id: number;
    name?: string | null;
    batch?: number | null;
    updatedAt: string;
    createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
    id: number;
    items: {
        title?: string | null;
        Relation?: {
            relationTo: 'pages';
            value: number | Page;
        } | null;
        sub_menu_1?: Navigation_Block[] | null;
        id?: string | null;
    }[];
    updatedAt?: string | null;
    createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Navigation_Block".
 */
export interface Navigation_Block {
    content?:
        | (
        | {
        items?:
            | {
            title?: string | null;
            page?: {
                relationTo: 'pages';
                value: number | Page;
            } | null;
            id?: string | null;
        }[]
            | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'SimpleMenu';
    }
        | {
        layout?: ('oneColumn' | 'twoColumns' | 'twoThirdsOneThird' | 'halfAndHalf' | 'threeColumns') | null;
        columnOne?:
            | {
            items?:
                | {
                title?: string | null;
                page?: {
                    relationTo: 'pages';
                    value: number | Page;
                } | null;
                id?: string | null;
            }[]
                | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'SimpleMenu';
        }[]
            | null;
        columnTwo?:
            | {
            items?:
                | {
                title?: string | null;
                page?: {
                    relationTo: 'pages';
                    value: number | Page;
                } | null;
                id?: string | null;
            }[]
                | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'SimpleMenu';
        }[]
            | null;
        columnThree?:
            | {
            items?:
                | {
                title?: string | null;
                page?: {
                    relationTo: 'pages';
                    value: number | Page;
                } | null;
                id?: string | null;
            }[]
                | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'SimpleMenu';
        }[]
            | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'columns-block';
    }
        )[]
        | null;
    id?: string | null;
    blockName?: string | null;
    blockType: 'NavigationBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-options".
 */
export interface SiteOption {
    id: number;
    siteTitle: string;
    siteDescription: string;
    siteLogo: number | Media;
    siteLogoSmall: number | Media;
    updatedAt?: string | null;
    createdAt?: string | null;
}
